// Copyright AmberAeolian. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace IC_FragmentTags
{
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GridFragment)
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IconFragment)
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StackableFragment)
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemNameFragment)
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PrimaryStatFragment)
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemTypeFragment)
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FlavorTextFragment)
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SellValueFragment)
	ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RequiredLevelFragment)

	namespace StatMod
	{
		ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_1)
		ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_2)
		ITEMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_3)
	}
}